### ISSUE TITLE
Wordpress - Safari (in-app) Detector

### ISSUE THREAD

**Issue by ernandozatariano** [Pierre-Lannoy/wp-device-detector#1]
Hi, congratulations for the great wordpress plugin! Device detector helps me to improve my website and my android/ios apps with webview.

I use the Device Detector to apply custom CSS for differents browsers / devices, and works very well! But i missing the dection for Safari (in-app) browsers. This is avaiable? Any prevision?

Tks again for the wonderfull plugin! Best regards!

**Comment by Pierre-Lannoy** [comment]
Hello @ernandozatariano and thanks for your kind words :)
Let me investigate on this to see how it is rendered now and how it should be...

**Comment by Pierre-Lannoy** [comment]
Hello @ernandozatariano.
Could you confirm that by in-app safari, you speak about browsing via apps (like Facebook, or Apple News)?

**Comment by ernandozatariano** [comment]
Hi! Yes, when you are browsing via apps in iOS, google analytics detect the Safari (in-app) Browser, like in the screenshot below:

![01](https://user-images.githubusercontent.com/63005352/81187715-c7e2a680-8f8a-11ea-9455-3e2e7be1f1cc.jpg)

Many app developers use a function called WebView. With this resource, its possible browser in external urls from an application. In android apps, Google Analytics recognizes that with the name "Android Webview", and Wp-Device-Detector recognizes that with "podd-client-name-chromewebview". 

![02](https://user-images.githubusercontent.com/63005352/81188934-5c013d80-8f8c-11ea-94ea-4cc20383012e.jpg)

When an app developer use the WebView function in iOS, Wp-Device-Detector not recognize Safari (in-app) like a browser.

You can read the official documentation about this function for iOS Developers here:

https://developer.apple.com/documentation/webkit/wkwebview

And maybe this article helps too: https://www.iflutter.in/flutter-webview/

Tks again! Best regards :)
