### ISSUE TITLE
Unable to detect Ubuntu

### ISSUE THREAD

**Issue by jhonny-oliveira** [Pierre-Lannoy/wp-device-detector#2]
Hi!

The plugin is unable to properly detect Ubuntu, it detects "GNU/Linux" instead.

Any ideas?

Environment
 - PHP 8.0.8 (cli) (built: Oct 26 2021 11:42:42) ( NTS )
 - WordPress: 5.8.2
 - Theme: Materialis

Thank you!
Jhonny

**Comment by Pierre-Lannoy** [comment]
Hi @jhonny-oliveira !
That's strange… Could you give me the user-agent string you have for this device?

**Comment by jhonny-oliveira** [comment]
Google says:
Your user agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

**Comment by jhonny-oliveira** [comment]
With Firefox, Ubuntu is properly detected. So, I guess this is a problem related to Chrome.

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by Pierre-Lannoy** [comment]
Yes, this is what I was writing to you…
This user agent is not correct and probably because of Chrome.
Let me investigate more…

**Comment by Pierre-Lannoy** [comment]
OK. I can confirm it's a Chrome related problem. I don't know if it's a "native error"… But it can't be fixed. Sorry for that.

**Comment by jhonny-oliveira** [comment]
No problem!
I will keep an eye out for the Chrome updates. I guess once they fix it, the plugin will automatically work.

Thank you @Pierre-Lannoy !
Jhonny Oliveira
https://xtradeb.net
