### ISSUE TITLE
Tools -> Devices is not working

### ISSUE THREAD

**Issue by jhonny-oliveira** [Pierre-Lannoy/wp-device-detector#3]
Hi!

when one selects Tools -> devices, one gets:

There has been a critical error on this website. Please check your site admin email inbox for instructions.

The following error shows in the httpd error log:

[php:error] [pid 3117] [client 192.168.123.1:45160] PHP Fatal error:  Uncaught Error: Undefined constant "IPLOCATOR_API_VERSION" in /var/www/wordpress/wp-content/plugins/device-detector/admin/partials/device-detector-admin-tools.php:16\nStack trace:\n#0 /var/www/wordpress/wp-content/plugins/device-detector/admin/class-device-detector-admin.php(264): include()\n#1 /var/www/wordpress/wp-includes/class-wp-hook.php(303): PODeviceDetector\\Plugin\\Device_Detector_Admin->get_tools_page()\n#2 /var/www/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()\n#3 /var/www/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action()\n#4 /var/www/wordpress/wp-admin/admin.php(259): do_action()\n#5 {main}\n  thrown in /var/www/wordpress/wp-content/plugins/device-detector/admin/partials/device-detector-admin-tools.php on line 16, referer: http://192.168.123.7/wp-admin/admin.php?page=perfopsone-tools

Environment
 - PHP 8.0.8 (cli) (built: Oct 26 2021 11:42:42) ( NTS )
 - WordPress: 5.8.2
 - Theme: Materialis

Thank you!

**Comment by Pierre-Lannoy** [comment]
And that's a huge good catch!
Many thanks to found it, it will be fixed and released on wp.org in some minutes.

**Comment by Pierre-Lannoy** [comment]
I've just released 3.0.1 on wp.org. This new version fixes the corresponding issue.
Thanks again.

**Comment by jhonny-oliveira** [comment]
This looks worse now. The site is down with:

[Wed Dec 15 21:29:51.850439 2021] [php:error] [pid 8330] [client 192.168.123.1:45362] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/wordpress/wp-content/plugins/device-detector/includes/libraries/decalog-sdk/Engine.php:297\nStack trace:\n#0 /var/www/wordpress/wp-content/plugins/device-detector/includes/libraries/autoload.php(28): include_once()\n#1 /var/www/wordpress/wp-content/plugins/device-detector/device-detector.php(71): {closure}()\n#2 /var/www/wordpress/wp-content/plugins/device-detector/device-detector.php(80): podd_run()\n#3 /var/www/wordpress/wp-settings.php(409): include_once('...')\n#4 /var/www/wordpress/wp-config.php(77): require_once('...')\n#5 /var/www/wordpress/wp-load.php(50): require_once('...')\n#6 /var/www/wordpress/wp-admin/admin.php(34): require_once('...')\n#7 /var/www/wordpress/wp-admin/update-core.php(10): require_once('...')\n#8 {main}\n  thrown in /var/www/wordpress/wp-content/plugins/device-detector/includes/libraries/decalog-sdk/Engine.php on line 297, referer: http://192.168.123.7/wp-admin/update-core.php

**Comment by Pierre-Lannoy** [comment]
OMG!
This is the price to pay for wanting to go too fast.
Working on a fix…

**Comment by Pierre-Lannoy** [comment]
Version 3.0.2 released on wp.org.
Thanks for the hint.

**Comment by jhonny-oliveira** [comment]
The problem is solved now!

Great plugin, btw!

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by Pierre-Lannoy** [comment]
Thanks <3

Don't hesitate to make a review if you like it…
